### ISSUE TITLE
EPIC: React Project Setup

### ISSUE THREAD

**Issue by mattthughes** [mattthughes/souls-like-gallery#27]
As a **developer** I can **deploy the site** so that **I can make sure the development project and the deployed project work as intended**

- [ ] install React and supporting Libraries
- [ ] Create base component
- [ ] Early Deployment to Heroku
