### ISSUE TITLE
EPIC: User Profile

### ISSUE THREAD

**Issue by mattthughes** [mattthughes/souls-like-gallery#28]
As a **site user** I can **Create, read and update my profile** so that **I can log into my account, keep my information secure**

- [ ] Create an account
- [ ] Update username
- [ ] Update Profile Picture
- [ ] Change Password
- [ ] Reset Password if I have forgot it
