### ISSUE TITLE
EPIC: Post Searching

### ISSUE THREAD

**Issue by mattthughes** [mattthughes/souls-like-gallery#30]
As a **site user** I can **search for posts to view posts that other users have posted** so that **I can find new posts I haven't seen**

Potential User Stories

- [ ] Search by Post Name

- [ ] Search by User name

- [ ]  Search by Keyword

- [ ] Sort by Popularity
